#!/usr/bin/env python
import json

print("Content-type: text/html\n")

fhandler = open("/home/jianxiong/eth_miner/config.txt", "rt")
value = fhandler.read().split('\n')

result = {}
for i in value:
	con = i.split(' ')
	result[con[0]] = con[1]

fhandler.close()

print(json.dumps(result))